services:
  inatviewer-production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:80"
    volumes: 
      - ./app/public/images:/srv/public/images
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M
